apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: fluent-bit-base

resources:
  - namespace.yaml
  - service_account.yaml
  - rbac.yaml
  - configmap.yaml
  - daemonset.yaml

commonLabels:
  app.kubernetes.io/name: fluent-bit
  app.kubernetes.io/component: logging
  app.kubernetes.io/part-of: observability

namespace: amazon-cloudwatch
