# Dev overrides for Karpenter

# Reduce replicas for dev
replicas: 1

# Verbose logging in dev
logLevel: debug
logEncoding: console

# Dev EKS cluster identifiers
clusterName: "max-weather-dev"

# IMPORTANT: Set this to your dev EKS API server endpoint before installing.
# You can get it from Terraform outputs (eks_cluster_endpoint) or `aws eks describe-cluster`.
clusterEndpoint: "https://7629DB42466E0342547DBE54E094C7B3.yl4.ap-southeast-2.eks.amazonaws.com"

aws:
  # Default instance profile for nodes launched by Karpenter in dev
  defaultInstanceProfile: "KarpenterNodeInstanceProfile-max-weather-dev"

# ServiceAccount annotations (e.g., IRSA role) can be set here when available
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::972709131469:role/max-weather-dev-karpenter-node"

# Enable default Provisioner and AWSNodeTemplate for dev
provisioner:
  enabled: true
  name: default
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.small", "t3.medium"]
  limits:
    resources:
      cpu: "8"
      memory: "16Gi"
  ttlSecondsAfterEmpty: 30
  providerRef:
    name: default

awsNodeTemplate:
  enabled: true
  name: default
  subnetSelector:
    kubernetes.io/cluster/name: "max-weather-dev"
  securityGroupSelector:
    kubernetes.io/cluster/name: "max-weather-dev"
  tags:
    Environment: dev


