apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: weather-api-dev

namespace: dev

resources:
  - ../../../base/weather-api

namePrefix: dev-

commonLabels:
  environment: dev
  tier: development

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml
  - secret-patch.yaml

images:
  - name: weather-api
    newName: 972709131469.dkr.ecr.ap-southeast-2.amazonaws.com/max-weather-dev
    newTag: latest-v1

replicas:
  - name: weather-api
    count: 1
