apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: weather-api-base

resources:
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app: weather-api
  component: api

images:
  - name: weather-api
    newTag: latest
