apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: weather-api-production
namespace: production
resources:
  - ../../../base/weather-api
namePrefix: prod-
commonLabels:
  environment: production
  tier: production
patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml
  - secret-patch.yaml
images:
  - name: weather-api
    newName: 972709131469.dkr.ecr.ap-southeast-2.amazonaws.com/max-weather-dev
    newTag: 1.0.3
replicas:
  - name: weather-api
    count: 3
