controller:
  replicaCount: 2

  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:REGION:ACCOUNT_ID:certificate/REPLACE-CERT-ID"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    targetPorts:
      http: http
      https: http
    ports:
      - name: http
        port: 80
        targetPort: http
      - name: https
        port: 443
        targetPort: http

  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    enable-real-ip: "true"
    ssl-redirect: "true"
    custom-http-errors: "404,500,502,503,504"
    proxy-buffer-size: "16k"
    proxy-body-size: "10m"
    proxy-read-timeout: "60"
    proxy-send-timeout: "60"

  extraArgs:
    default-backend-service: "default/error-pages"

defaultBackend:
  enabled: false

rbac:
  create: true

serviceAccount:
  create: true

